development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rygless
  pool:     5
  username:
  password:

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rygless_test
  pool:     5
  username:
  password: